#!/usr/bin/env python3
"""Turn the supplied Roobert files into the webfont the page actually loads.

    python3 tools/build-fonts.py        # src/fonts/*  →  site/assets/fonts/*
    python3 tools/build-css.py

**It ships the variable font, not the statics.** Twelve static cuts came with
the trial; the VF is one file that covers all of them and two things they
cannot:

  * `wght` 300–900 continuous, so `font-weight:600` is 600 rather than the
    nearest static — and the statics are stamped 650 and 750, not 600 and 700,
    so every weight in the stylesheet would otherwise land on a neighbour.
  * a **`MONO` axis**, 0–100. Roobert carries its own monospace, which is what
    lets the page keep three type registers in ONE family: `--fm` is the same
    font at `MONO:100`, not a second typeface and not a proportional face
    pretending to be data.

Three passes, each of which earns its place:

  1. **Pin `ital` to 0.** There is no `font-style:italic` anywhere in this
     page's CSS. The slant axis is most of the file: 253 KB → 165 KB.
  2. **Subset.** Latin, Latin-1, the punctuation and symbols the page uses,
     and a generous margin around them — not the exact glyphs in today's
     copy, or tomorrow's copy breaks. 165 KB → 64 KB. The Devanagari, CJK
     and Hangul in the language menu were never in Roobert and were always
     falling back; that is unchanged.
  3. **WOFF2.**

One file, one request, 64 KB, replacing six Google-hosted families across
two extra connections.

The `@font-face` block is generated into `system.css` between the two markers
below — two faces on the same URL, so the browser downloads it once. Each src
carries the hash of its own bytes: `build-css.py` stamps assets named in
index.html and does not look inside the stylesheet, so a font replaced in
place would otherwise serve from cache forever.
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src', 'fonts')
OUT = os.path.join(ROOT, 'site', 'assets', 'fonts')
CSS = os.path.join(ROOT, 'src', 'css', 'system.css')

FAMILY = 'Roobert TRIAL'
MONO_FAMILY = 'Roobert TRIAL Mono'
STEM = 'roobert-var'

BEGIN = '/* ==== FONTS: generated by tools/build-fonts.py — do not edit ==== */'
END = '/* ==== end fonts ==== */'

# Deliberately wider than the copy. Latin + Latin-1 + Latin Extended-A picks up
# every accented name a customer quote might carry; the punctuation blocks pick
# up the em dash, the curly quotes, the ellipsis, ×, ·, → and the currency signs
# a pricing page grows later.
UNICODES = ','.join([
    'U+0000-00FF',            # basic Latin + Latin-1 (ç ê ñ ©)
    'U+0100-017F',            # Latin Extended-A
    'U+02B0-02FF',            # spacing modifiers
    'U+0300-036F',            # combining marks
    'U+2000-206F',            # general punctuation — — ’ … ·
    'U+2070-209F',            # super/subscripts
    'U+20A0-20BF',            # currency
    'U+2100-214F',            # letterlike — ™ №
    'U+2190-21FF',            # arrows
    'U+2200-22FF',            # maths — × ∂ ∑
    'U+25A0-25FF',            # geometric shapes — the bullets and dots
    'U+FB00-FB06',            # ligatures
    'U+FEFF', 'U+FFFD',
])
FEATURES = 'kern,liga,clig,calt,ccmp,tnum,lnum,onum,pnum,case,mark,mkmk,frac,zero,ordn,sups,subs'


def main():
    try:
        from fontTools.ttLib import TTFont
        from fontTools.varLib import instancer
        from fontTools import subset
        import brotli                                  # noqa: F401
    except ImportError:
        sys.exit('pip3 install --break-system-packages fonttools brotli')

    vf = next((os.path.join(SRC, n) for n in sorted(os.listdir(SRC))
               if n.lower().endswith(('.ttf', '.otf')) and 'VF' in n), None)
    if not vf:
        sys.exit('no variable font in src/fonts/ — expected a *VF*.ttf')

    raw = os.path.getsize(vf)
    f = TTFont(vf)
    axes = {a.axisTag: (a.minValue, a.maxValue) for a in f['fvar'].axes}
    for need in ('wght', 'MONO'):
        if need not in axes:
            sys.exit('the supplied VF has no %s axis — axes are %s' % (need, list(axes)))

    # 1 · the page has no italics; the slant axis is most of the file
    if 'ital' in axes:
        instancer.instantiateVariableFont(f, {'ital': 0}, inplace=True, updateFontNames=False)
    pinned = os.path.join(OUT, STEM + '.pinned.ttf')
    os.makedirs(OUT, exist_ok=True)
    f.save(pinned)
    f.close()

    # 2 + 3 · subset and compress
    dest = os.path.join(OUT, STEM + '.woff2')
    subset.main([pinned, '--output-file=' + dest, '--flavor=woff2',
                 '--unicodes=' + UNICODES, '--layout-features=' + FEATURES,
                 '--no-hinting', '--desubroutinize'])
    os.remove(pinned)

    check = TTFont(dest)
    kept = {a.axisTag: (a.minValue, a.maxValue) for a in check['fvar'].axes}
    glyphs = check['maxp'].numGlyphs
    check.close()
    digest = hashlib.sha1(open(dest, 'rb').read()).hexdigest()[:8]

    lo, hi = kept['wght']
    face = ('@font-face{\n'
            '  font-family:"%s";\n'
            '  src:url(assets/fonts/%s.woff2?v=%s) format("woff2-variations"),\n'
            '      url(assets/fonts/%s.woff2?v=%s) format("woff2");\n'
            '  font-weight:%d %d;\n'
            '  font-style:normal;\n'
            '  font-display:swap;%s\n'
            '}')
    rules = [
        face % (FAMILY, STEM, digest, STEM, digest, lo, hi, ''),
        face % (MONO_FAMILY, STEM, digest, STEM, digest, lo, hi,
                '\n  /* the SAME file — one download. Roobert carries its own\n'
                '     monospace on a variation axis, so the utility register is\n'
                '     this typeface rather than a second one. */\n'
                '  font-variation-settings:"MONO" 100;'),
    ]

    block = BEGIN + '\n' + '\n'.join(rules) + '\n' + END
    css = open(CSS, encoding='utf-8').read()
    if BEGIN in css:
        css = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: block,
                     css, count=1, flags=re.S)
    else:
        css = block + '\n\n' + css
    open(CSS, 'w', encoding='utf-8').write(css)

    print('%s\n  %d KB raw → %d KB woff2   axes %s   %d glyphs   ?v=%s'
          % (os.path.basename(vf), raw // 1024, os.path.getsize(dest) // 1024,
             ' '.join('%s %g-%g' % (k, *v) for k, v in kept.items()), glyphs, digest))
    print('  2 faces (%s, %s) on one URL → src/css/system.css' % (FAMILY, MONO_FAMILY))
    return 0


if __name__ == '__main__':
    sys.exit(main())
