#!/usr/bin/env python3
"""Turn the supplied Roobert files into the webfont the page actually loads.

    mkdir -p src/fonts && cp ~/Downloads/RoobertTRIAL*.otf src/fonts/
    python3 tools/build-fonts.py
    python3 tools/build-css.py

What it does, and why each part exists:

  * **Converts to WOFF2.** A foundry trial ships .otf or .ttf; both are two to
    four times the size of the same outlines in WOFF2, and this page's whole
    budget is three webfonts. Conversion is `fontTools` + `brotli`, which is a
    BUILD dependency — the site still ships zero JS libraries.

  * **Reads the weight and the slant out of the file, not out of its name.**
    `OS/2.usWeightClass` and `post.italicAngle` are what the renderer will use.
    A trial download called `-SemiBold` that is stamped 600 internally and a
    differently-named cut that is stamped 500 have to end up on the right
    `font-weight`, or `font-weight:600` in the stylesheet silently synthesises
    a fake bold from the 400 and every heading gets slightly wrong.

  * **Emits the @font-face block into system.css**, between the two markers
    below, so the block is generated and never hand-edited. Each `src` carries
    `?v=<hash of the file's own bytes>` — `build-css.py` stamps assets named in
    index.html and does not look inside the stylesheet, so a font replaced in
    place would otherwise keep serving from cache forever (the exact failure
    the image stamping was added to end).

  * **`font-display:swap`** on every face: text renders in the fallback and
    swaps, rather than being invisible while a 40KB file loads.

Prints a table of what it found so the mapping can be checked by eye, and
fails loudly if a weight the stylesheet asks for is missing.
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src', 'fonts')
OUT = os.path.join(ROOT, 'site', 'assets', 'fonts')
CSS = os.path.join(ROOT, 'src', 'css', 'system.css')

FAMILY = 'Roobert TRIAL'
BEGIN = '/* ==== FONTS: generated by tools/build-fonts.py — do not edit ==== */'
END = '/* ==== end fonts ==== */'

# what the stylesheet asks for; a missing one is synthesised by the browser
# and looks like a rendering bug rather than a missing file
REQUIRED = {300, 400, 500, 600, 700}


def faces():
    if not os.path.isdir(SRC):
        sys.exit('no src/fonts/ — put the Roobert files there first')
    from fontTools.ttLib import TTFont

    found = []
    for name in sorted(os.listdir(SRC)):
        if not name.lower().endswith(('.otf', '.ttf', '.woff', '.woff2')):
            continue
        path = os.path.join(SRC, name)
        f = TTFont(path, lazy=True)
        weight = int(getattr(f['OS/2'], 'usWeightClass', 400))
        # italicAngle is the honest answer; the fsSelection bit and the file
        # name both get set wrong in trial cuts often enough to not trust them
        italic = float(getattr(f['post'], 'italicAngle', 0)) != 0.0
        f.close()
        found.append({'src': path, 'weight': weight, 'italic': italic})
    if not found:
        sys.exit('src/fonts/ has no font files in it')
    return found


def main():
    os.makedirs(OUT, exist_ok=True)
    try:
        from fontTools.ttLib import TTFont            # noqa: F401
        import brotli                                 # noqa: F401
    except ImportError:
        sys.exit('pip3 install --break-system-packages fonttools brotli')
    from fontTools.ttLib import TTFont

    rules, table, have = [], [], set()
    for face in sorted(faces(), key=lambda f: (f['italic'], f['weight'])):
        stem = 'roobert-%d%s' % (face['weight'], '-italic' if face['italic'] else '')
        dest = os.path.join(OUT, stem + '.woff2')
        f = TTFont(face['src'])
        f.flavor = 'woff2'
        f.save(dest)
        f.close()
        digest = hashlib.sha1(open(dest, 'rb').read()).hexdigest()[:8]
        have.add((face['weight'], face['italic']))
        table.append('  %-34s → %-22s %4d %s  %d KB'
                     % (os.path.basename(face['src']), stem + '.woff2',
                        face['weight'], 'italic' if face['italic'] else '      ',
                        os.path.getsize(dest) // 1024))
        rules.append(
            '@font-face{\n'
            '  font-family:"%s";\n'
            '  src:url(assets/fonts/%s.woff2?v=%s) format("woff2");\n'
            '  font-weight:%d;\n'
            '  font-style:%s;\n'
            '  font-display:swap;\n'
            '}' % (FAMILY, stem, digest, face['weight'],
                   'italic' if face['italic'] else 'normal'))

    css = open(CSS, encoding='utf-8').read()
    block = BEGIN + '\n' + '\n'.join(rules) + '\n' + END
    if BEGIN in css:
        css = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: block,
                     css, count=1, flags=re.S)
    else:
        css = block + '\n\n' + css
    open(CSS, 'w', encoding='utf-8').write(css)

    print('\n'.join(table))
    missing = sorted(w for w in REQUIRED if (w, False) not in have)
    print('\n%d faces → src/css/system.css' % len(rules))
    if missing:
        print('MISSING upright weights the stylesheet asks for: %s\n'
              '  the browser will synthesise these, which looks like a bug.\n'
              '  Either supply the cut or move the rules onto a weight you have.'
              % ', '.join(map(str, missing)))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
