#!/usr/bin/env python3
"""Run this repo's CSS gates against the MIGRATED stylesheet.

    python3 tools/gate-migrated.py [path-to/okou-homepage.css]

The site moved to `vm0-ai/vm0-marketing` on 2026-09-02 and Tong's instruction
was that the rules stay HERE and are consulted, not copied over there. That
keeps the product repo clean and it costs one thing: the checks have to reach
across.

Two of them reach across unchanged, and two cannot without help:

  * `unguarded_dark_blocks`, `shorthand_wipes_image`, `grid_height_without_rows`
    are layer-agnostic — they read one file and mean the same thing.
  * `dead_declarations` and `shorthand_eats_longhand` are LAYER-AWARE. In this
    repo `base.css` (mock internals) and `system.css` (the design layer) are two
    files, and system.css is concatenated last precisely so it wins; both checks
    exclude that on purpose. Flattened into one stylesheet the exclusion has
    nothing to key on and they report the architecture as a fault — 155 and 7
    the first time this was run.

So the boundary is restored before the checks run. `build-css.py` joins the two
sources with a newline, and system.css opens with the generated FONTS banner, so
that banner is the seam. Split there, write two temporary files with the
original names, and every check means what it meant before.

`audit.js` and axe need none of this: they run against a rendered page, so point
them at the dev server or a PR preview.

KNOWN NOISE, 2 findings. `.slackui{color}` and `.btn{border-radius}` come back as
"overridden by an identical later selector". They are NOT regressions from the
port: running this same script against this repo's own `site/styles.css` gives
the identical pair, and `tokens.py` against the true two-file sources gives 0.
They are an artifact of reading a BUILT stylesheet — `build-css.py` prunes rules
for absent classes, and a pair that the sources keep in different contexts can
end up keyed the same once flattened. Treat the target number as **2, not 0**,
and investigate anything above it.
"""
import importlib.util
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT = Path('/home/user/workspace/marketing/vite-ssr/app/_okou-home/okou-homepage.css')
SEAM = '/* ==== FONTS: generated by tools/build-fonts.py'


def load_tokens():
    spec = importlib.util.spec_from_file_location('tk', ROOT / 'tools' / 'tokens.py')
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def split_layers(css, out_dir):
    """base.css | system.css, cut at the seam build-css.py leaves behind."""
    i = css.find(SEAM)
    if i < 0:
        raise SystemExit('seam not found — has build-css.py changed its order?')
    base, system = css[:i], css[i:]
    b = out_dir / 'base.css'
    s = out_dir / 'system.css'
    b.write_text(base, encoding='utf-8')
    s.write_text(system, encoding='utf-8')
    return b, s


def main():
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT
    if not target.exists():
        raise SystemExit(f'not found: {target}')
    css = target.read_text(encoding='utf-8')
    tk = load_tokens()
    total = 0
    with tempfile.TemporaryDirectory() as tmp:
        b, s = split_layers(css, Path(tmp))
        print(f'{target}  {target.stat().st_size / 1024:.0f} KB')
        print(f'  split at the FONTS seam → base {b.stat().st_size / 1024:.0f} KB'
              f' · system {s.stat().st_size / 1024:.0f} KB\n')
        paths = [b, s]
        checks = (
            ('longhands reset by a later shorthand', tk.shorthand_eats_longhand, paths),
            ('dark-media rules with no light guard', tk.unguarded_dark_blocks, paths),
            ('`background:` clearing a background-image', tk.shorthand_wipes_image, paths),
            ('sized grids with an implicit row track', tk.grid_height_without_rows, paths),
        )
        for label, fn, arg in checks:
            hits = fn(arg)
            print(f'=== {label}: {len(hits)}')
            for h in hits[:10]:
                print('   ', h)
            total += len(hits)
        dead = tk.dead_declarations(paths)
        n = sum(len(v) - 1 for v in dead.values())
        print(f'\n=== declarations overridden by an identical later selector: {n}')
        for (f0, media, sel, prop), lines in sorted(dead.items(), key=lambda x: -len(x[1]))[:10]:
            print(f'   {f0}  {sel[:34]:<34} {prop:<15} {lines}')
        total += n
    print(f'\nTOTAL: {total}')
    return 0 if total == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
